### PR TITLE
Update TestingPullRequest.md

### PR DESCRIPTION
**Pull request by luyajun0205**

### CODE REVIEW

**Comment by v-peliao** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[TestingPullRequest.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/prtest/TestingPullRequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-azuredotnet/testingpullrequest?branch=pr-en-us-4) | [Details](#user-content-TestingPullRequest.md)
[addFile.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/prtest/addFile.md) | :white_check_mark:Succeeded | |

<a name="TestingPullRequest.md"></a>
### [TestingPullRequest.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/prtest/TestingPullRequest.md)
 - **Line 4**: **[Warning]** Invalid file link:(~/../nonexisted1.md).
 - **Line 5**: **[Warning]** Invalid file link:(~/../nonexisted2.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/../nonexisted3.md).
 - **Line 9**: **[Warning]** The content part of NOTE/WARNING/CAUTION/IMPORTANT/NEXT syntax is suggested to start in a new line.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C10%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707100314109067-4%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[TestingPullRequest.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/prtest/TestingPullRequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-azuredotnet/testingpullrequest?branch=pr-en-us-4) | [Details](#user-content-TestingPullRequest.md)
[addFile.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/prtest/addFile.md) | :white_check_mark:Succeeded | |

<a name="TestingPullRequest.md"></a>
### [TestingPullRequest.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/prtest/TestingPullRequest.md)
 - **Line 4**: **[Warning]** Invalid file link:(~/../nonexisted1.md).
 - **Line 5**: **[Warning]** Invalid file link:(~/../nonexisted2.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/../nonexisted3.md).
 - **Line 9**: **[Warning]** The content part of NOTE/WARNING/CAUTION/IMPORTANT/NEXT syntax is suggested to start in a new line.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C10%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707100702578544-4%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[TestingPullRequest.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/prtest/TestingPullRequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-azuredotnet/testingpullrequest?branch=pr-en-us-4) | [Details](#user-content-TestingPullRequest.md)
[addFile.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/prtest/addFile.md) | :white_check_mark:Succeeded | |

<a name="TestingPullRequest.md"></a>
### [TestingPullRequest.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/prtest/TestingPullRequest.md)
 - **Line 4**: **[Warning]** Invalid file link:(~/../nonexisted1.md).
 - **Line 5**: **[Warning]** Invalid file link:(~/../nonexisted2.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/../nonexisted3.md).
 - **Line 9**: **[Warning]** The content part of NOTE/WARNING/CAUTION/IMPORTANT/NEXT syntax is suggested to start in a new line.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C10%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707100856235912-4%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[TestingPullRequest.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/prtest/TestingPullRequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-azuredotnet/testingpullrequest?branch=pr-en-us-4) | [Details](#user-content-TestingPullRequest.md)
[addFile.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/prtest/addFile.md) | :white_check_mark:Succeeded | |

<a name="TestingPullRequest.md"></a>
### [TestingPullRequest.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/prtest/TestingPullRequest.md)
 - **Line 4**: **[Warning]** Invalid file link:(~/../nonexisted1.md).
 - **Line 5**: **[Warning]** Invalid file link:(~/../nonexisted2.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/../nonexisted3.md).
 - **Line 9**: **[Warning]** The content part of NOTE/WARNING/CAUTION/IMPORTANT/NEXT syntax is suggested to start in a new line.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C28%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707280854526558-4%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[TestingPullRequest.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/prtest/TestingPullRequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-azuredotnet/testingpullrequest?branch=pr-en-us-4) | [Details](#user-content-TestingPullRequest.md)
[addFile.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/prtest/addFile.md) | :white_check_mark:Succeeded | |

<a name="TestingPullRequest.md"></a>
### [TestingPullRequest.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/prtest/TestingPullRequest.md)
 - **Line 4**: **[Warning]** Invalid file link:(~/../nonexisted1.md).
 - **Line 5**: **[Warning]** Invalid file link:(~/../nonexisted2.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/../nonexisted3.md).
 - **Line 9**: **[Warning]** The content part of NOTE/WARNING/CAUTION/IMPORTANT/NEXT syntax is suggested to start in a new line.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C28%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707280855028264-4%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[TestingPullRequest.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/prtest/TestingPullRequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-azuredotnet/testingpullrequest?branch=pr-en-us-4) | [Details](#user-content-TestingPullRequest.md)
[addFile.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/prtest/addFile.md) | :white_check_mark:Succeeded | |

<a name="TestingPullRequest.md"></a>
### [TestingPullRequest.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/prtest/TestingPullRequest.md)
 - **Line 4**: **[Warning]** Invalid file link:(~/../nonexisted1.md).
 - **Line 5**: **[Warning]** Invalid file link:(~/../nonexisted2.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/../nonexisted3.md).
 - **Line 9**: **[Warning]** The content part of NOTE/WARNING/CAUTION/IMPORTANT/NEXT syntax is suggested to start in a new line.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C31%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707310122259473-4%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[TestingPullRequest.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/prtest/TestingPullRequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-azuredotnet/testingpullrequest?branch=pr-en-us-4) | [Details](#user-content-TestingPullRequest.md)
[addFile.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/prtest/addFile.md) | :white_check_mark:Succeeded | |

<a name="TestingPullRequest.md"></a>
### [TestingPullRequest.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/prtest/TestingPullRequest.md)
 - **Line 4**: **[Warning]** Invalid file link:(~/../nonexisted1.md).
 - **Line 5**: **[Warning]** Invalid file link:(~/../nonexisted2.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/../nonexisted3.md).
 - **Line 9**: **[Warning]** The content part of NOTE/WARNING/CAUTION/IMPORTANT/NEXT syntax is suggested to start in a new line.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C31%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707310539475760-4%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
