### PR TITLE
Resolve syncing conflicts from master-sync-work to master

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from master-sync-work to master.

### CODE REVIEW

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet, working directory: W:\o0tt-s, target branch: master, target branch commit: 976914f558b3b9a9ff5eb6c54aba87d1c8f362db, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C24%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707240108534235-10%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Micosnow** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet, working directory: W:\bwmh-s, target branch: master, target branch commit: 976914f558b3b9a9ff5eb6c54aba87d1c8f362db, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C24%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707241857146867-10%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Micosnow** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet, working directory: W:\find-s, target branch: master, target branch commit: 976914f558b3b9a9ff5eb6c54aba87d1c8f362db, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C24%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707241858323346-10%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet, working directory: W:\p4hp-s, target branch: master, target branch commit: 976914f558b3b9a9ff5eb6c54aba87d1c8f362db, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C24%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707242124474798-10%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet, working directory: W:\40fy-s, target branch: master, target branch commit: 976914f558b3b9a9ff5eb6c54aba87d1c8f362db, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C25%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707251734378434-10%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot merge commit 7a022e9d9270c71d2aff6918e85f4316ca89d7c2 in branch master-sync-work of repository https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet into branch master (commit 976914f558b3b9a9ff5eb6c54aba87d1c8f362db)

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C25%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707251737498143-10%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet, working directory: W:\zxso-s, target branch: master, target branch commit: 976914f558b3b9a9ff5eb6c54aba87d1c8f362db, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C25%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707251949510190-10%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\2lzb-o-unknown\raw-\i3yivob2.nlv\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\2lzb-o-unknown\raw-\i3yivob2.nlv\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C27%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707270745172688-10%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet, working directory: W:\2yxn-s, target branch: master, target branch commit: 976914f558b3b9a9ff5eb6c54aba87d1c8f362db, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C27%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707271837129067-10%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\2srw-o-f88f2293\raw-\zt4uspcl.ota\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\2srw-o-f88f2293\raw-\zt4uspcl.ota\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C28%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707280628020013-10%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
