### PR TITLE
merge master into live-based

### PR DESCRIPTION
**Pull request by luyajun0205**

### CODE REVIEW

**Comment by v-susu** [comment]
OPS Build status updates of commit _[b4f530d](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/pull/57/commits/b4f530d6e607e03a8d12f9c83d6927e6cbfa9406)_: 

:clock10: **Preparing**: average preparing time is _11 min(s)_

**Comment by v-susu** [comment]
OPS Build status updates of commit _[b4f530d](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/pull/57/commits/b4f530d6e607e03a8d12f9c83d6927e6cbfa9406)_: 

:clock10: **Preparing**: average preparing time is _11 min(s)_

**Comment by staceyhong** [comment]
OPS Build status updates of commit _[b4f530d](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/pull/57/commits/b4f530d6e607e03a8d12f9c83d6927e6cbfa9406)_: 

:clock10: **Full build**: average full build time is _100 min(s) 5 sec(s)_ [calculated from last _4_ build(s)]

> Note: A full build takes more time than an incremental build.  This is the expected behavior of the build system.

**Comment by luyajun0205** [comment]
OPS Build status updates of commit _[b4f530d](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/pull/57/commits/b4f530d6e607e03a8d12f9c83d6927e6cbfa9406)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[docfx.json](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/docfx.json) | :white_check_mark:Succeeded | |
[docs-ref-toc/top_level_toc.yml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/docs-ref-toc/top_level_toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C28%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201901280608351396-57%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jVYT3vR%2FxFDF0vPF%2BAsYF8%2BtIOAkl6MDLZFI2qjBWW0%3D&st=2019-01-28T08%3A00%3A07Z&se=2019-02-28T08%3A05%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
