### PR TITLE
merge master into live-based branch

### PR DESCRIPTION
**Pull request by luyajun0205**

### CODE REVIEW

**Comment by v-peliao** [comment]
OPS Build status updates of commit _[e233b8b](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/pull/56/commits/e233b8b94c32e034e45bc5f94630fe5b5b2a01d6)_: 

:clock10: **Preparing**: average preparing time is _11 min(s) 2 sec(s)_

**Comment by staceyhong** [comment]
OPS Build status updates of commit _[e233b8b](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/pull/56/commits/e233b8b94c32e034e45bc5f94630fe5b5b2a01d6)_: 

:clock10: **Incremental building**: average incremental building time is _19 min(s) 15 sec(s)_

**Comment by v-susu** [comment]
OPS Build status updates of commit _[e233b8b](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/pull/56/commits/e233b8b94c32e034e45bc5f94630fe5b5b2a01d6)_: 

:clock10: **Preparing**: average preparing time is _11 min(s) 1 sec(s)_

**Comment by v-peliao** [comment]
OPS Build status updates of commit _[e233b8b](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/pull/56/commits/e233b8b94c32e034e45bc5f94630fe5b5b2a01d6)_: 

:clock10: **Incremental building**: average incremental building time is _20 min(s) 30 sec(s)_

**Comment by staceyhong** [comment]
OPS Build status updates of commit _[e233b8b](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/pull/56/commits/e233b8b94c32e034e45bc5f94630fe5b5b2a01d6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/Microsoft.Azure.NotificationHubs.NotificationDetails.yml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/api/Microsoft.Azure.NotificationHubs.NotificationDetails.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-azuredotnet/api/microsoft.azure.notificationhubs.notificationdetails.-ctor?branch=pr-en-us-56) | [Details](#user-content-api%2FMicrosoft.Azure.NotificationHubs.NotificationDetails.yml)
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[docfx.json](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/docfx.json) | :white_check_mark:Succeeded | |
[xml/FrameworksIndex/azure-dotnet.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/FrameworksIndex/azure-dotnet.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/CloudTableClient.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/CloudTableClient.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/AccessCondition.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/AccessCondition.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/AccessConditionType.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/AccessConditionType.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/ChangeFeedOptions.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/ChangeFeedOptions.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/ConnectionMode.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/ConnectionMode.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/ConnectionPolicy.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/ConnectionPolicy.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/DocumentClient.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/DocumentClient.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/DocumentResponse`1.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/DocumentResponse%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/FeedOptions.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/FeedOptions.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/FeedResponse`1.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/FeedResponse%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/IDocumentResponse`1.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/IDocumentResponse%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/IFeedResponse`1.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/IFeedResponse%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/IMediaResponse.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/IMediaResponse.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/IPartitionResolver.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/IPartitionResolver.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/IResourceResponseBase.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/IResourceResponseBase.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/IResourceResponse`1.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/IResourceResponse%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/IStoredProcedureResponse`1.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/IStoredProcedureResponse%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/MediaOptions.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/MediaOptions.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/MediaReadMode.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/MediaReadMode.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/MediaResponse.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/MediaResponse.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/Protocol.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/Protocol.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/RequestOptions.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/RequestOptions.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/ResourceResponseBase.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/ResourceResponseBase.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/ResourceResponse`1.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/ResourceResponse%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/RetryOptions.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/RetryOptions.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/StoredProcedureResponse`1.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/StoredProcedureResponse%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Client/UriFactory.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/UriFactory.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Linq/DocumentQueryException.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Linq/DocumentQueryException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Linq/DocumentQueryable.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Linq/DocumentQueryable.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Linq/IDocumentQuery.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Linq/IDocumentQuery.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Linq/IDocumentQuery`1.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Linq/IDocumentQuery%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Linq/UserDefinedFunctionProvider.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Linq/UserDefinedFunctionProvider.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Partitioning/Range`1.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Partitioning/Range%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Spatial/BoundingBox.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Spatial/BoundingBox.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Spatial/Crs.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Spatial/Crs.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Spatial/CrsType.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Spatial/CrsType.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Spatial/Geometry.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Spatial/Geometry.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Spatial/GeometryOperationExtensions.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Spatial/GeometryOperationExtensions.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Spatial/GeometryParams.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Spatial/GeometryParams.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Spatial/GeometryType.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Spatial/GeometryType.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Spatial/GeometryValidationResult.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Spatial/GeometryValidationResult.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Spatial/LineString.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Spatial/LineString.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Spatial/LinearRing.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Spatial/LinearRing.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Spatial/LinkedCrs.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Spatial/LinkedCrs.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Spatial/NamedCrs.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Spatial/NamedCrs.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Documents.Spatial/Point.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Spatial/Point.xml) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
<a name="api%2FMicrosoft.Azure.NotificationHubs.NotificationDetails.yml"></a>
### [api/Microsoft.Azure.NotificationHubs.NotificationDetails.yml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master/api/Microsoft.Azure.NotificationHubs.NotificationDetails.yml)
 - **[Warning]** 2 invalid cross reference(s) &quot;Microsoft.Azure.NotificationHubs.NotificationHubClient.SendNotificationImplAsync&quot;, &quot;Microsoft.Azure.NotificationHubs.NotificationHubClient.SendScheduledNotificationImplAsync&quot;.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C8%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201901080104484552-56%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=SqN%2FjLf1Zt5W6Qe71S%2BE6FlC%2FIzZYAp4gxjYojkR9x0%3D&st=2019-01-08T02%3A07%3A03Z&se=2019-02-08T02%3A12%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
