### PR TITLE
Resolve syncing conflicts from master-sync-work to master

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from master-sync-work to master.

### CODE REVIEW

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet, working directory: W:\wj2w-s, target branch: master, target branch commit: 48a500be3d06356d6ac958e486b9b383c7cee516, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C13%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201806131733445125-43%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=n1PnOsZPLa%2Fb4ojhUPs3i%2BQyHXuVq6cWRZuiwbVOO88%3D&st=2018-06-13T17%3A36%3A23Z&se=2018-07-14T17%3A41%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet, working directory: W:\btyn-s, target branch: master, target branch commit: 48a500be3d06356d6ac958e486b9b383c7cee516, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C13%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201806131835569437-43%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=WLyA0GbcrO8jIO652LdHct4xPf4eC9afs1AVkhiJBe4%3D&st=2018-06-13T18%3A38%3A57Z&se=2018-07-14T18%3A43%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet, working directory: W:\11c4-s, target branch: master, target branch commit: 48a500be3d06356d6ac958e486b9b383c7cee516, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C13%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201806132113554557-43%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=QF4IzI9sGQtLtuiGQu1Oy3zTpCwskcxyTTfS%2BMUeE1k%3D&st=2018-06-13T21%3A17%3A31Z&se=2018-07-14T21%3A22%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet, working directory: W:\g2pm-s, target branch: master, target branch commit: 48a500be3d06356d6ac958e486b9b383c7cee516, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C14%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201806142043293664-43%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7PevgqcnkOnA5jgiKjh6%2FGeT%2FLJyeo5K%2B79BdBOtYy4%3D&st=2018-06-14T20%3A45%3A36Z&se=2018-07-15T20%3A50%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[_zip/msdn.4.5.2.zip](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/_zip/msdn.4.5.2.zip) | :white_check_mark:Succeeded | |
[api/overview/azure/containerinstance.md](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/api/overview/azure/containerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azuredotnet/api/overview/azure/containerinstance?branch=pr-en-us-43) |
[docs-ref-toc/top_level_toc.yml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/docs-ref-toc/top_level_toc.yml) | :white_check_mark:Succeeded | |
[xml/FrameworksIndex/azure-dotnet.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/FrameworksIndex/azure-dotnet.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/CloudTableClient.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.CosmosDB.Table/CloudTableClient.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IBlank.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IBlank.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IDefinition.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IDefinition.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithAgentPool.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithAgentPool.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithCreate.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithCreate.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithDiagnostics.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithDiagnostics.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithGroup.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithGroup.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithLinux.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithLinux.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithLinuxRootUsername.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithLinuxRootUsername.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithLinuxSshKey.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithLinuxSshKey.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithMasterDnsPrefix.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithMasterDnsPrefix.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithMasterNodeCount.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithMasterNodeCount.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithMasterOSDiskSize.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithMasterOSDiskSize.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithMasterStorageProfile.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithMasterStorageProfile.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithMasterVMSize.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithMasterVMSize.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithOrchestrator.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithOrchestrator.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithServicePrincipalProfile.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithServicePrincipalProfile.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithSubnet.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Definition/IWithSubnet.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Update/IUpdate.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Update/IUpdate.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Update/IWithDiagnostics.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Update/IWithDiagnostics.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Update/IWithUpdateAgentPoolCount.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerService.Update/IWithUpdateAgentPoolCount.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IBlank`1.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IBlank%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IDefinition`1.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IDefinition%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithAttach`1.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithAttach%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithLeafDomainLabel`1.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithLeafDomainLabel%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithOSDiskSize`1.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithOSDiskSize%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithOSType`1.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithOSType%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithPorts`1.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithPorts%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithStorageProfile`1.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithStorageProfile%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithSubnet`1.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithSubnet%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithVMSize`1.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceAgentPool.Definition/IWithVMSize%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IBlank.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IBlank.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IDefinition.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IDefinition.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithAgentPool.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithAgentPool.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithCreate.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithCreate.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithDnsPrefix.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithDnsPrefix.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithGroup.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithGroup.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithKeyVaultSecret.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithKeyVaultSecret.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithLinuxRootUsername.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithLinuxRootUsername.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithLinuxSshKey.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithLinuxSshKey.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithServicePrincipalClientId.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithServicePrincipalClientId.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithServicePrincipalProfile.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithServicePrincipalProfile.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithVersion.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition/IWithVersion.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Update/IUpdate.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Update/IUpdate.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Update/IWithUpdateAgentPoolCount.xml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/master-sync-work/xml/Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Update/IWithUpdateAgentPoolCount.xml) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C15%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201806150713232435-43%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=yq3gAADPqSyrI3EPiRNV6q8CrD%2F37PpWwA4nRJRoIWs%3D&st=2018-06-15T07%3A29%3A24Z&se=2018-07-16T07%3A34%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
