### PR TITLE
merge master into live-based branch

### PR DESCRIPTION
**Pull request by luyajun0205**

### CODE REVIEW

**Comment by staceyhong** [comment]
OPS Build status updates of commit _[b8152af](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/pull/55/commits/b8152afe0ebf08f1dc4545017fbab42e62afb1ba)_: 

:clock10: **Preparing**: average preparing time is _11 min(s) 10 sec(s)_

**Comment by luyajun0205** [comment]
OPS Build status updates of commit _[b8152af](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/pull/55/commits/b8152afe0ebf08f1dc4545017fbab42e62afb1ba)_: 

:clock10: **Full build**: average full build time is not available, there is no data for this repository.

> Note: A full build takes more time than an incremental build.  This is the expected behavior of the build system.

**Comment by v-susu** [comment]
OPS Build status updates of commit _[b8152af](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/pull/55/commits/b8152afe0ebf08f1dc4545017fbab42e62afb1ba)_: 

:clock10: **Preparing**: average preparing time is _11 min(s) 10 sec(s)_

**Comment by v-peliao** [comment]
OPS Build status updates of commit _[b8152af](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/pull/55/commits/b8152afe0ebf08f1dc4545017fbab42e62afb1ba)_: 

:clock10: **Full build**: average full build time is not available, there is no data for this repository.

> Note: A full build takes more time than an incremental build.  This is the expected behavior of the build system.

**Pull request closed without merging**
