### PR TITLE
Resolve syncing conflicts from live-sync-work to live

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from live-sync-work to live.

### CODE REVIEW

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet, working directory: W:\x4bs-s, target branch: live, target branch commit: 5bda7adc223e4f31f271115bcc75f1624cbd2464, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C24%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707240529374816-11%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet, working directory: W:\kryl-s, target branch: live, target branch commit: 5bda7adc223e4f31f271115bcc75f1624cbd2464, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C24%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707241858336090-11%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Micosnow** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet, working directory: W:\zrz3-s, target branch: live, target branch commit: 5bda7adc223e4f31f271115bcc75f1624cbd2464, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C24%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707242106317687-11%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot merge commit e48073c4f44ed94bca5e62d72438fc94a657fea7 in branch live-sync-work of repository https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet into branch live (commit 5bda7adc223e4f31f271115bcc75f1624cbd2464)

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C25%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707251734100455-11%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot merge commit d3ac1266d5d06e5102e8d24b6ea084d02c65e66f in branch live-sync-work of repository https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet into branch live (commit 5bda7adc223e4f31f271115bcc75f1624cbd2464)

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C25%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707251740037827-11%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/live-sync-work/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/OPS-E2E-Prod/azure-docs-sdk-dotnet/blob/live-sync-work/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\y11g-o-unknown\raw-\5ufqfiv2.4po\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\y11g-o-unknown\raw-\5ufqfiv2.4po\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C27%5C1d39ca21-9140-7188-562e-44ca707262e0%5CPullRequest%5C201707270746569014-11%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
